name = "blue-cloud-c7c2"
main = "src/index.js"
compatibility_date = "2026-09-17"

[triggers]
crons = ["0 21 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "global-discovery"
database_id = "f9c82884-642f-4697-9435-df0b6d8897bc"
