// Expanding source pool. Core RSS stays in index.js.
// These feeds are unlocked gradually so a single Workflow run does not fetch everything.

export const EXTRA_RSS_SOURCES = [
  { name: "NHK World", base_url: "https://www3.nhk.or.jp/nhkworld/", feed_url: "https://www3.nhk.or.jp/nhkworld/en/news/rss.xml", language: "en", country: "JP", region: "Asia", source_type: "catalog" },
  { name: "Japan Times", base_url: "https://www.japantimes.co.jp/", feed_url: "https://www.japantimes.co.jp/feed/", language: "en", country: "JP", region: "Asia", source_type: "catalog" },
  { name: "Korea Herald", base_url: "https://www.koreaherald.com/", feed_url: "https://www.koreaherald.com/rss", language: "en", country: "KR", region: "Asia", source_type: "catalog" },
  { name: "The Hindu International", base_url: "https://www.thehindu.com/", feed_url: "https://www.thehindu.com/news/international/feeder/default.rss", language: "en", country: "IN", region: "Asia", source_type: "catalog" },
  { name: "Dawn", base_url: "https://www.dawn.com/", feed_url: "https://www.dawn.com/feeds/home", language: "en", country: "PK", region: "Asia", source_type: "catalog" },
  { name: "Taipei Times", base_url: "https://www.taipeitimes.com/", feed_url: "https://www.taipeitimes.com/xml/index.rss", language: "en", country: "TW", region: "Asia", source_type: "catalog" },
  { name: "Focus Taiwan", base_url: "https://focustaiwan.tw/", feed_url: "https://focustaiwan.tw/rss", language: "en", country: "TW", region: "Asia", source_type: "catalog" },
  { name: "South China Morning Post", base_url: "https://www.scmp.com/", feed_url: "https://www.scmp.com/rss/91/feed", language: "en", country: "HK", region: "Asia", source_type: "catalog" },
  { name: "The Jakarta Post", base_url: "https://www.thejakartapost.com/", feed_url: "https://www.thejakartapost.com/rss", language: "en", country: "ID", region: "Asia", source_type: "catalog" },
  { name: "Bangkok Post", base_url: "https://www.bangkokpost.com/", feed_url: "https://www.bangkokpost.com/rss/data/topstories.xml", language: "en", country: "TH", region: "Asia", source_type: "catalog" },
  { name: "Channel News Asia", base_url: "https://www.channelnewsasia.com/", feed_url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml", language: "en", country: "SG", region: "Asia", source_type: "catalog" },
  { name: "ABC Australia", base_url: "https://www.abc.net.au/news/", feed_url: "https://www.abc.net.au/news/feed/51120/rss.xml", language: "en", country: "AU", region: "Oceania", source_type: "catalog" },
  { name: "RNZ World", base_url: "https://www.rnz.co.nz/", feed_url: "https://www.rnz.co.nz/rss/world.xml", language: "en", country: "NZ", region: "Oceania", source_type: "catalog" },
  { name: "AllAfrica", base_url: "https://allafrica.com/", feed_url: "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf", language: "en", country: "multi", region: "Africa", source_type: "catalog" },
  { name: "Daily Maverick", base_url: "https://www.dailymaverick.co.za/", feed_url: "https://www.dailymaverick.co.za/dmrss/", language: "en", country: "ZA", region: "Africa", source_type: "catalog" },
  { name: "Mail and Guardian", base_url: "https://mg.co.za/", feed_url: "https://mg.co.za/feed/", language: "en", country: "ZA", region: "Africa", source_type: "catalog" },
  { name: "Premium Times", base_url: "https://www.premiumtimesng.com/", feed_url: "https://www.premiumtimesng.com/feed", language: "en", country: "NG", region: "Africa", source_type: "catalog" },
  { name: "The East African", base_url: "https://www.theeastafrican.co.ke/", feed_url: "https://www.theeastafrican.co.ke/tea/rss", language: "en", country: "KE", region: "Africa", source_type: "catalog" },
  { name: "Arab News", base_url: "https://www.arabnews.com/", feed_url: "https://www.arabnews.com/rss.xml", language: "en", country: "SA", region: "Middle East", source_type: "catalog" },
  { name: "Middle East Eye", base_url: "https://www.middleeasteye.net/", feed_url: "https://www.middleeasteye.net/rss", language: "en", country: "multi", region: "Middle East", source_type: "catalog" },
  { name: "Times of Israel", base_url: "https://www.timesofisrael.com/", feed_url: "https://www.timesofisrael.com/feed/", language: "en", country: "IL", region: "Middle East", source_type: "catalog" },
  { name: "Haaretz", base_url: "https://www.haaretz.com/", feed_url: "https://www.haaretz.com/srv/haaretz-latest-headlines", language: "en", country: "IL", region: "Middle East", source_type: "catalog" },
  { name: "El Pais English", base_url: "https://english.elpais.com/", feed_url: "https://feeds.elpais.com/mrss-s/pages/ep/site/english.elpais.com/portada", language: "en", country: "ES", region: "Europe", source_type: "catalog" },
  { name: "Politico Europe", base_url: "https://www.politico.eu/", feed_url: "https://www.politico.eu/feed/", language: "en", country: "EU", region: "Europe", source_type: "catalog" },
  { name: "Der Spiegel International", base_url: "https://www.spiegel.de/international/", feed_url: "https://www.spiegel.de/international/index.rss", language: "en", country: "DE", region: "Europe", source_type: "catalog" },
  { name: "The Local Europe", base_url: "https://www.thelocal.com/", feed_url: "https://www.thelocal.com/feeds/rss.php", language: "en", country: "multi", region: "Europe", source_type: "catalog" },
  { name: "Irish Times World", base_url: "https://www.irishtimes.com/", feed_url: "https://www.irishtimes.com/rss/world.xml", language: "en", country: "IE", region: "Europe", source_type: "catalog" },
  { name: "MercoPress", base_url: "https://en.mercopress.com/", feed_url: "https://en.mercopress.com/rss/latest_news", language: "en", country: "UY", region: "Latin America", source_type: "catalog" },
  { name: "Buenos Aires Herald", base_url: "https://buenosairesherald.com/", feed_url: "https://buenosairesherald.com/feed", language: "en", country: "AR", region: "Latin America", source_type: "catalog" },
  { name: "Mexico News Daily", base_url: "https://mexiconewsdaily.com/", feed_url: "https://mexiconewsdaily.com/feed/", language: "en", country: "MX", region: "Latin America", source_type: "catalog" },
  { name: "The Conversation Global", base_url: "https://theconversation.com/global", feed_url: "https://theconversation.com/articles.atom", language: "en", country: "multi", region: "global", source_type: "catalog" },
  { name: "Nature News", base_url: "https://www.nature.com/news", feed_url: "https://www.nature.com/nature.rss", language: "en", country: "GB", region: "global", source_type: "catalog" },
  { name: "ScienceDaily", base_url: "https://www.sciencedaily.com/", feed_url: "https://www.sciencedaily.com/rss/all.xml", language: "en", country: "US", region: "global", source_type: "catalog" },
  { name: "Phys.org", base_url: "https://phys.org/", feed_url: "https://phys.org/rss-feed/", language: "en", country: "multi", region: "global", source_type: "catalog" },
  { name: "Smithsonian Magazine", base_url: "https://www.smithsonianmag.com/", feed_url: "https://www.smithsonianmag.com/rss/latest/", language: "en", country: "US", region: "global", source_type: "catalog" },
  { name: "Hyperallergic", base_url: "https://hyperallergic.com/", feed_url: "https://hyperallergic.com/feed/", language: "en", country: "US", region: "global", source_type: "catalog" },
  { name: "ArchDaily", base_url: "https://www.archdaily.com/", feed_url: "https://www.archdaily.com/feed", language: "en", country: "multi", region: "global", source_type: "catalog" },
  { name: "Pitchfork News", base_url: "https://pitchfork.com/", feed_url: "https://pitchfork.com/feed/feed-news/rss", language: "en", country: "US", region: "global", source_type: "catalog" },
  { name: "The Atlantic", base_url: "https://www.theatlantic.com/", feed_url: "https://www.theatlantic.com/feed/all/", language: "en", country: "US", region: "North America", source_type: "catalog" },
  { name: "ProPublica", base_url: "https://www.propublica.org/", feed_url: "https://www.propublica.org/feeds/propublica/main", language: "en", country: "US", region: "North America", source_type: "catalog" },
  { name: "Rest of World", base_url: "https://restofworld.org/", feed_url: "https://restofworld.org/feed/latest", language: "en", country: "multi", region: "global", source_type: "catalog" },
  { name: "African Arguments", base_url: "https://africanarguments.org/", feed_url: "https://africanarguments.org/feed/", language: "en", country: "multi", region: "Africa", source_type: "catalog" },
  { name: "Himal Southasian", base_url: "https://www.himalmag.com/", feed_url: "https://www.himalmag.com/feed/", language: "en", country: "multi", region: "Asia", source_type: "catalog" },
  { name: "New Mandala", base_url: "https://www.newmandala.org/", feed_url: "https://www.newmandala.org/feed/", language: "en", country: "multi", region: "Asia", source_type: "catalog" },
  { name: "Mongabay", base_url: "https://news.mongabay.com/", feed_url: "https://news.mongabay.com/feed/", language: "en", country: "multi", region: "global", source_type: "catalog" },
  { name: "Carbon Brief", base_url: "https://www.carbonbrief.org/", feed_url: "https://www.carbonbrief.org/feed/", language: "en", country: "GB", region: "global", source_type: "catalog" },
  { name: "Stat News", base_url: "https://www.statnews.com/", feed_url: "https://www.statnews.com/feed/", language: "en", country: "US", region: "global", source_type: "catalog" },
  { name: "Ars Technica", base_url: "https://arstechnica.com/", feed_url: "https://feeds.arstechnica.com/arstechnica/index", language: "en", country: "US", region: "global", source_type: "catalog" },
  { name: "The Register", base_url: "https://www.theregister.com/", feed_url: "https://www.theregister.com/headlines.atom", language: "en", country: "GB", region: "global", source_type: "catalog" },
  { name: "Canary Media", base_url: "https://www.canarymedia.com/", feed_url: "https://www.canarymedia.com/rss", language: "en", country: "US", region: "North America", source_type: "catalog" }
];

export const EXTRA_GOOGLE_RADARS = [
  { name: "Google News Radar - health", query: "public health OR vaccine OR hospital OR outbreak OR epidemic" },
  { name: "Google News Radar - energy", query: "energy OR electricity OR oil OR gas OR renewable OR grid" },
  { name: "Google News Radar - courts", query: "court OR verdict OR constitution OR tribunal OR lawsuit" },
  { name: "Google News Radar - infrastructure", query: "infrastructure OR port OR railway OR housing OR water supply" },
  { name: "Google News Radar - agriculture", query: "agriculture OR harvest OR drought OR fertilizer OR livestock" },
  { name: "Google News Radar - local culture", query: "festival OR heritage OR indigenous OR museum OR craft" }
];
